implement main program

diff --git a/src/offsite-cert b/src/offsite-cert
--- a/src/offsite-cert
+++ b/src/offsite-cert
@@ -1,14 +1,16 @@
-#/bin/bash
+#!/bin/bash
 
-set -x
+#set -x
+
+#CONFIGFILE=/etc/offsite-cert/domains
+CONFIGFILE=conf/domains
 
 read -r -d '' AWKPRG <<-'EOF'
 	BEGIN {
 	  inCert = 0
 	}
 
-
-	/-----BEGIN CERTIFICATE-----/ {
+	/^-----BEGIN CERTIFICATE-----/ {
 	  inCert = 1
 	}
 
@@ -16,18 +18,70 @@ read -r -d '' AWKPRG <<-'EOF'
 	  print
 	}
 
-	/-----END CERTIFICATE-----/ {
+	/^-----END CERTIFICATE-----/ {
 	  inCert = 0
 	}
 EOF
 
-DESTCERTFILE=/etc/nginx/ssl.cer/example.com.crt
-TMPCERTFILE=/tmp/example.com.pem
+downloadCert() {
+  local connectAddress="$1"
+  local serverName="$2"
+  local certFile="$3"
+  local tmpDownloadFile="$4"
+  local tmpCertFile="$5"
 
-openssl s_client -connect example.com:443 -servername www.example.com -showcerts </dev/null 2>/dev/null | awk "$AWKPRG" > "$TMPCERTFILE"
+  if ! openssl s_client -connect "$connectAddress" -servername "$serverName" -showcerts </dev/null 2>/dev/null >"$tmpDownloadFile"; then
+    echo "ERROR: download failed"
+    return 1
+  fi
 
-if ! diff -q "$DESTCERTFILE" "$TMPCERTFILE" >/dev/null; then
-  mv "$TMPCERTFILE" "$DESTCERTFILE"
-else
-  rm "$TMPCERTFILE"
-fi
+  if ! awk "$AWKPRG" <"$tmpDownloadFile" >"$tmpCertFile"; then
+    echo "ERROR: cert extraction failed"
+    return 1
+  fi
+
+  if [ -f "$certFile" ] && diff -q "$tmpCertFile" "$certFile" >/dev/null; then
+    echo "SUCCESS: the certificate has not changed"
+    return 0
+  fi
+
+  if ! cp "$tmpCertFile" "$certFile"; then
+    echo "ERROR: copy of new certificate to destination failed"
+    return 1
+  fi
+
+  echo "SUCCESS: the new certificate was copied to its destination"
+  return 0
+}
+
+processDomain() {
+  local connectAddress="$1"
+  local serverName="$2"
+  local certFile="$3"
+  local tmpDownloadFile
+  local tmpCertFile
+  local retval
+
+  tmpDownloadFile=$(mktemp) || exit
+  tmpCertFile=$(mktemp) || exit
+
+  downloadCert "$connectAddress" "$serverName" "$certFile" "$tmpDownloadFile" "$tmpCertFile"
+  retval=$?
+
+  rm "$tmpDownloadFile"
+  rm "$tmpCertFile"
+
+  return $retval
+}
+
+sed -e '/^\s*$/d;/^\s*#/d;$a\' "$CONFIGFILE" | while read CONNECTADDRESS SERVERNAME CERTFILE; do
+  echo "----------------------------------------"
+  echo "CONNECTADDRESS: $CONNECTADDRESS"
+  echo "SERVERNAME    : $SERVERNAME"
+  echo "CERTFILE      : $CERTFILE"
+  if processDomain "$CONNECTADDRESS" "$SERVERNAME" "$CERTFILE"; then
+    echo "success for domain: $SERVERNAME"
+  else
+    echo "failure for domain: $SERVERNAME"
+  fi
+done
